import type { Insight } from '../types';

/**
 * Reports, research and commentary by IP3's team, taken from the publication lists in their CVs.
 * Authors are credited as the publication credits them; "contributed" means the CV states a contribution
 * to a report written by others. Links point to the publisher's own copy.
 */
export const insights: Insight[] = [
  {
    id: 'gearing-up-manufacturing-bangladesh',
    status: 'published',
    kind: 'Report',
    title: 'Gearing Up for the Future of Manufacturing in Bangladesh',
    authors: 'Yunfan Gu, Gaurav Nayyar and Siddharth Sharma; IP3 contributed the Bangladesh survey work',
    publisher: 'World Bank',
    year: 2021,
    href: 'http://hdl.handle.net/10986/35879',
    summary: 'How far Bangladeshi manufacturers have adopted new technology, what holds them back, and the reforms that would help, drawing on a survey of 1,200 firms.',
    people: ['mohammad-syful-hoque'],
    engagement: 'fat-survey-bangladesh',
  },
  {
    id: 'bridging-technological-divide',
    status: 'published',
    kind: 'Report',
    title: 'Bridging the Technological Divide: Technology Adoption by Firms in Developing Countries',
    authors: 'Xavier Cirera, Diego Comin and Marcio Cruz; IP3 contributed the Bangladesh survey work',
    publisher: 'World Bank',
    year: 2022,
    href: 'https://openknowledge.worldbank.org/entities/publication/ee3abd08-33db-41b9-86f7-9b3176632083',
    summary: 'A World Bank flagship on why firms in developing countries lag in adopting technology, built on the Firm-level Adoption of Technology survey.',
    people: ['mohammad-syful-hoque'],
    engagement: 'fat-survey-bangladesh',
  },
  {
    id: 'building-resilience-education-bangladesh',
    status: 'published',
    kind: 'Book chapter',
    title: "Building resilience in Bangladesh's education system: Evidence and policy lessons",
    authors: 'Kazi Iqbal and Siban Shahana',
    publisher: 'Asian Development Bank Institute, in Building Resilience in Education Systems (eds. E. M. King and D. Suryadarma)',
    year: 2024,
    href: 'https://www.adb.org/publications/building-resilience-in-education-systems',
    summary: 'What Bangladesh learned about keeping children learning through shocks, and the policy lessons for a more resilient education system.',
    people: ['siban-shahana'],
    engagement: '',
  },
  {
    id: 'adolescent-nutrition-cost-effective',
    status: 'published',
    kind: 'Report',
    title: 'Taking Collective Action to Improve Adolescent Nutrition in Bangladesh: Investing in Cost-Effective Interventions',
    authors: 'World Bank; cost-benefit analysis by Shafiun Nahin Shimul with the James P Grant School of Public Health, BRAC University',
    publisher: 'World Bank',
    year: 2019,
    href: 'http://documents.worldbank.org/curated/en/777311566457641589/Taking-Collective-Action-to-Improve-Adolescent-Nutrition-in-Bangladesh-Investing-in-Cost-Effective-Interventions',
    summary: 'Which adolescent nutrition interventions give the most return for the money in Bangladesh, based on an economic evaluation of each.',
    people: ['prof-dr-shafiun-shimul'],
    engagement: '',
  },
  {
    id: 'fsi-three-asian-countries',
    status: 'published',
    kind: 'Report',
    title: 'Financial Soundness Indicators for Financial Sector Stability: A Tale of Three Asian Countries',
    authors: 'Asian Development Bank; Bangladesh study by Mohammad Syful Hoque',
    publisher: 'Asian Development Bank',
    year: 2015,
    href: 'https://www.adb.org/sites/default/files/publication/173687/fsi-3-asian-countries.pdf',
    summary: 'How Bangladesh and two other Asian economies compile and use financial soundness indicators to watch over financial stability.',
    people: ['mohammad-syful-hoque'],
    engagement: '',
  },
  {
    id: 'property-tax-valuation-model',
    status: 'published',
    kind: 'Journal article',
    title: 'Applying a spatially based, weighted parametric valuation model to address property taxation challenges for developing countries',
    authors: 'Mohammad Syful Hoque',
    publisher: 'Journal of Property Tax Assessment & Administration, 16(2)',
    year: 2019,
    href: 'https://researchexchange.iaao.org/jptaa/vol16/iss2/2',
    summary: 'A GIS-based method for valuing property fairly where market data are thin, so that cities in developing countries can raise property tax.',
    people: ['mohammad-syful-hoque'],
    engagement: '',
  },
  {
    id: 'input-subsidies-crop-diversity',
    status: 'published',
    kind: 'Journal article',
    title: 'Input subsidies and crop diversity on family farms in Burkina Faso',
    authors: 'Sibbir Ahmad, Melinda Smale, Veronique Theriault and Eugenie Maiga',
    publisher: 'Journal of Agricultural Economics',
    year: 2023,
    href: '',
    summary: 'Whether fertiliser and seed subsidies change the mix of crops that family farms grow.',
    people: ['dr-sibbir-ahmad'],
    engagement: '',
  },
  {
    id: 'cereal-cropping-smallholders',
    status: 'published',
    kind: 'Book chapter',
    title: 'Can cereal-based cropping technologies only improve the food and livelihood security of the poor smallholders in marginal areas of Bangladesh?',
    authors: 'M. A. Malek, M. S. Hoque, J. Yesmin and M. L. Haque',
    publisher: 'Springer (book chapter)',
    year: 2016,
    href: 'https://link.springer.com/chapter/10.1007/978-3-319-25718-1_16',
    summary: 'Evidence on whether new cereal-cropping technologies alone can lift food and livelihood security for poor smallholders in marginal areas.',
    people: ['mohammad-syful-hoque'],
    engagement: '',
  },
  {
    id: 'gender-gap-employment-fe',
    status: 'published',
    kind: 'Commentary',
    title: 'The gender gap in employment: women have a low share in quality, gainful jobs',
    authors: 'Mohammad Syful Hoque',
    publisher: 'The Financial Express',
    year: 2019,
    href: 'https://today.thefinancialexpress.com.bd/26th-anniversary-issue-1/women-have-low-share-in-quality-gainful-jobs-1573546939',
    summary: 'Why women in Bangladesh remain under-represented in quality jobs despite rising participation.',
    people: ['mohammad-syful-hoque'],
    engagement: '',
  },
  {
    id: 'wealth-inequality-property-tax-fe',
    status: 'published',
    kind: 'Commentary',
    title: 'Wealth inequality: property tax can close the gap',
    authors: 'Mohammad Syful Hoque',
    publisher: 'The Financial Express',
    year: 2019,
    href: 'https://thefinancialexpress.com.bd/views/reviews/wealth-inequality-property-tax-can-close-the-gap-1553960303',
    summary: 'The case for a fairer, better-administered property tax as a tool against wealth inequality in Bangladesh.',
    people: ['mohammad-syful-hoque'],
    engagement: '',
  },
];
