import type { Engagement } from '../types';

/**
 * Selected engagements, 2018 to date.
 *
 * Source: the IP3 team's CVs, chiefly Mohammad Syful Hoque's CV (World Bank FORM TECH-6, signed
 * September 2026, and the EU-format CV of January 2025), as collected in the portfolio repository
 * mdsyfulhoque-afk/portfolio-web-claude (content/portfolio.json). IP3 confirmed on 2 October 2026
 * that these assignments may be presented as IP3's work and that the World Bank, ADB, the European
 * Commission and Sida (the Embassy of Sweden) may be named.
 *
 * Rules applied:
 *  - Client, place, period, role and reference are taken from the CVs as written.
 *  - Figures (firms surveyed, interviews, model horizons) are kept only where the CV states them.
 *  - `challenge` and `approach` are the case story. They describe the problem and the work done,
 *    never outcomes the sources do not report.
 *  - Work before 2018, or delivered through another firm, is kept as `verify` so it stays in the
 *    editor but off the site.
 */
export const portfolio: Engagement[] = [
  {
    id: 'climate-early-warning-adb',
    status: 'published',
    featured: true,
    title: 'Increasing investment in early warning systems for climate and disaster resilience',
    client: 'Asian Development Bank (ADB)',
    institutions: ['Asian Development Bank'],
    role: 'Economic and financial analysis specialist (international)',
    reference: 'ADB TA 10103-REG (regional TA 57055-001)',
    place: 'Bangladesh, Cambodia, Kazakhstan, Kyrgyz Republic, Lao PDR, Maldives, Mongolia, Nepal, Tajikistan and Uzbekistan',
    period: 'September 2025 – December 2026',
    start: 2025,
    end: 0,
    places: ['BD', 'KHM', 'KAZ', 'KGZ', 'LAO', 'MDV', 'MNG', 'NPL', 'TJK', 'UZB'],
    summary:
      'Design and start-up of a multi-hazard early warning facility that helps ten ADB member countries identify, prepare and finance early warning investments at scale.',
    challenge:
      'Early warning systems save lives and assets, but across Asia they are under-funded and fragmented: hazard monitoring, alerting and last-mile dissemination sit with different agencies, and few countries have investment-ready proposals. ADB set out to create a facility that turns that gap into a pipeline of financeable projects.',
    approach: [
      'Rapid diagnostics of hydromet, hazard and alerting gaps, with stakeholder mapping and country consultations.',
      'A facility blueprint covering governance, financing instruments, eligibility and the safeguards interface.',
      'Investment concept notes and screening templates, with pilot concepts prioritised for Bangladesh and Cambodia.',
      'Costing toolkits and cost-benefit models, budget notes and procurement plans.',
      'Standard operating procedures and technical specifications for multi-channel alerting: cell broadcast, SMS, voice, FM radio and community channels.',
      'A monitoring and evaluation logframe aligned with the Sendai Framework and SDG 13.',
      'Financial evaluation packages, WACC benchmarks and operation and maintenance sustainability over asset life.',
      'Economic and financial analysis chapters for three country investment frameworks, and donor-ready proposal material.',
    ],
    links: [],
    photo: '',
    services: ['economic-assessment', 'climate-esg', 'merla'],
    sectors: ['climate-energy', 'public-governance'],
    note: 'Current assignment (intermittent). Source: CV, FORM TECH-6.',
  },
  {
    id: 'nextgen-madrasah-adb',
    status: 'published',
    featured: true,
    title: 'NextGen Secondary Education Program: madrasah education',
    client: 'Asian Development Bank (ADB)',
    institutions: ['Asian Development Bank', 'Ministry of Education'],
    role: 'Economist and financial analyst',
    reference: 'Feasibility study, ADB TA-6950-BAN',
    place: 'Bangladesh',
    period: 'January 2025 – continuing',
    start: 2025,
    end: 0,
    places: ['BD'],
    summary:
      'Technical, financial and institutional feasibility of a nationwide modernisation of Dakhil and Alim madrasahs, aligned with Vision 2041 and the 8th Five-Year Plan.',
    challenge:
      'Many secondary and higher-secondary madrasahs sit outside the reach of recent reform projects. Classrooms, laboratories, digital infrastructure and teacher development lag behind, and the schools are exposed to climate shocks. The government and ADB needed to know which investments would raise quality and inclusion, and whether they would pay off.',
    approach: [
      'Audit of the teaching and learning environment: infrastructure, classroom practice and gender-sensitive learning conditions.',
      'Proposal to roll out the Dakhil Vocational Program in 495 selected madrasahs.',
      'Design and costing of ICT, science and social science laboratories and solar-powered learning spaces.',
      'Review of religious and general curricula against the National Curriculum Framework, with an e-content strategy.',
      'Assessment of classroom vulnerability to climate shocks, with retrofitting and green energy recommendations.',
      'Economic and financial cost-benefit analysis (ENPV, EIRR) of infrastructure, teacher training and continuing professional development.',
    ],
    links: [],
    photo: '',
    services: ['economic-assessment', 'program-survey-design'],
    sectors: ['education-skills'],
    note: 'Current assignment. Source: CV, FORM TECH-6.',
  },
  {
    id: 'nextgen-tvet-adb',
    status: 'published',
    featured: false,
    title: 'NextGen Secondary Education Program: technical and vocational education (TVET)',
    client: 'Asian Development Bank (ADB)',
    institutions: ['Asian Development Bank', 'Ministry of Education'],
    role: 'Economist and financial analyst',
    reference: 'Feasibility study, ADB TA-6950-BAN',
    place: 'Bangladesh',
    period: 'January 2024 – December 2024',
    start: 2024,
    end: 2024,
    places: ['BD'],
    summary:
      'Feasibility of a five-year, nationwide transformation of secondary and higher-secondary TVET institutions, especially non-MPO and independent institutes.',
    challenge:
      'Bangladesh\'s labour market is changing faster than its technical and vocational schools. Skills mismatches are growing with automation and the Fourth Industrial Revolution, and the institutions that need the most help are often outside government funding schemes.',
    approach: [
      'Labour-market and demand analysis: skills mismatch and future workforce needs.',
      'Review of TVET policy documents, the ASPR 2023 and earlier reform projects (STEP, SEIP, ASSET).',
      'SWOT and gap assessments across curriculum, digital content, gender inclusion and access for learners with special needs.',
      'Environmental and climate risk analysis of TVET infrastructure.',
      'Financial and economic cost-benefit modelling using national shadow-pricing parameters.',
      'Mapping of the institutional and legal capacity of the Directorate of Technical Education and the Bangladesh Technical Education Board.',
      'Interviews, focus groups and inter-agency dialogue with the Ministry of Education and its directorates.',
    ],
    links: [],
    photo: '',
    services: ['economic-assessment', 'program-survey-design'],
    sectors: ['education-skills'],
    note: 'Source: CV, FORM TECH-6.',
  },
  {
    id: 'nextgen-primary-gpe',
    status: 'published',
    featured: false,
    title: 'NextGen primary education: blended learning and digital transformation',
    client: 'Asian Development Bank (ADB), with the Ministry of Primary and Mass Education',
    institutions: ['Asian Development Bank', 'Global Partnership for Education', 'Ministry of Primary and Mass Education'],
    role: 'Economist and financial analyst',
    reference: 'Feasibility study under the Global Partnership for Education Program Development Grant',
    place: 'Bangladesh',
    period: 'June 2022 – October 2023',
    start: 2022,
    end: 2023,
    places: ['BD'],
    summary:
      'Feasibility study for a national project to scale blended learning and digital transformation across pre-primary and primary education.',
    challenge:
      'After the pandemic closures, primary education needed learning that could continue through disruption, including climate disasters, and that could reach every child. The question was which digital and AI-supported tools were technically and financially feasible at national scale.',
    approach: [
      'Technical feasibility of digital and AI-powered learning and assessment interventions.',
      'Market and institutional analysis for digital content, learning management systems and real-time assessment.',
      'Risk analysis for climate, disaster resilience and continuity of learning.',
      'Financial and economic cost-benefit models in line with Planning Division and ADB guidelines.',
      'Engagement with the Ministry, the Directorate of Primary Education and other stakeholders.',
    ],
    links: [],
    photo: '',
    services: ['economic-assessment'],
    sectors: ['education-skills'],
    note: 'Source: CV, FORM TECH-6.',
  },
  {
    id: 'education-feasibility-adb',
    status: 'published',
    featured: true,
    title: 'Feasibility study for new secondary and madrasah education projects',
    client: 'Asian Development Bank (ADB)',
    institutions: ['Asian Development Bank', 'Ministry of Education'],
    role: 'Economist and financial analyst',
    reference: 'ADB TA-6950-BAN: Supporting Education Sector Projects (56088-001)',
    place: 'Bangladesh',
    period: 'January 2022 – December 2023',
    start: 2022,
    end: 2023,
    places: ['BD'],
    summary:
      'The first economic and financial feasibility study of its kind in Bangladesh\'s education sector, assessing the viability of the proposed New Secondary and Madrasah Education Projects.',
    challenge:
      'Education projects in Bangladesh had rarely been appraised the way infrastructure is: with a full economic and financial case. The government needed to know whether the proposed secondary and madrasah projects were viable, what they would cost, and what could go wrong.',
    approach: [
      'Review of government policy, consultation records and existing EdTech interventions in secondary education.',
      'Market and demand analysis and SWOT assessment.',
      'Economic and financial cost-benefit analysis: net present value, benefit-cost ratio and internal rate of return.',
      'Risk and sensitivity analysis, varying key assumptions across scenarios.',
      'Cost estimates for the proposed interventions, the output plan and the implementation timeline.',
      'Technical and engineering options analysis, and human resources and administrative support analysis.',
      'Feasibility study reports prepared to Planning Commission requirements.',
    ],
    links: [],
    photo: '',
    services: ['economic-assessment'],
    sectors: ['education-skills'],
    note:
      'Source: CV, FORM TECH-6 and EU CV. The EU CV names Prof. Dr. M A Mannan (IP3 Senior Consulting Advisor) as team leader of the NSEP feasibility study.',
  },
  {
    id: 'green-industrial-transition-rmg',
    status: 'published',
    featured: true,
    title: 'Securing the green transition of the textile and ready-made garment sector',
    client: 'Embassy of Sweden in Bangladesh (Sida) and the Centre for Policy Dialogue',
    institutions: ['Embassy of Sweden (Sida)', 'Centre for Policy Dialogue'],
    role: 'Led the research and implementation team',
    reference: 'Research and advocacy programme',
    place: 'Bangladesh',
    period: 'January 2022 – June 2023',
    start: 2022,
    end: 2023,
    places: ['BD', 'BD-dhaka'],
    summary:
      'An 18-month research and advocacy programme on the barriers to, and drivers of, a green transition in Bangladesh\'s largest export industry, built on a survey of 400 randomly selected firms, 120 key informant interviews and 8 focus group discussions.',
    challenge:
      'The garment industry employs millions, many of them women, and faces rising pressure from buyers and regulators to cut emissions. Factories were unsure what green technology would cost, where finance could come from, and which rules applied. Without evidence, policy could not help them move.',
    approach: [
      'Designed the study from proposal to research method, questionnaires and analysis.',
      'Led the survey "Barriers to Green Transition" across 400 randomly selected firms, with 120 key informant interviews and 8 focus group discussions.',
      'Mapped policies, regulations, incentives and green finance, and the obstacles firms face in financing renewable energy.',
      'Assessed firms\' knowledge, interest and capacity to adopt green practices across the global value chain.',
      'Consulted government agencies, banks, investors and factory owners on financing gaps.',
      'Prepared policy briefs, including the case for a carbon (green) tax and incentives for renewable energy investment.',
    ],
    links: [],
    photo: 'rmg-floor',
    services: ['climate-esg', 'program-survey-design', 'macro-sector-policy'],
    sectors: ['climate-energy', 'private-sector'],
    note: 'Source: EU CV (400 firms, 120 KIIs, 8 FGDs; the old site said 7 FGDs, corrected from the CV).',
  },
  {
    id: 'payra-seaport-advisory',
    status: 'published',
    featured: false,
    title: 'Economic and financial advice to the Payra Port Authority',
    client: 'Payra Port Authority, Government of Bangladesh',
    institutions: ['Payra Port Authority'],
    role: 'Economic advisor',
    reference: 'Detailed techno-economic feasibility study and conceptual port master planning',
    place: 'Patuakhali, Bangladesh',
    period: 'April 2018 – December 2018',
    start: 2018,
    end: 2018,
    places: ['BD-payra'],
    summary:
      'Technical advice to the Payra Port Authority on the economic prospects of Payra seaport, including a 15-year financial model and governance models with PPP frameworks.',
    challenge:
      'A new deep-sea port is one of the largest public investments a country makes. The Port Authority needed independent advice to make sure the economic and financial case in the master plan prepared by third-party consultants was sound.',
    approach: [
      'Advised the Port Authority\'s management on the economic prospects of the seaport.',
      'Worked to ensure accurate economic and financial feasibility analysis in the third-party consultants\' report.',
      'Project cost-benefit, economic and financial analysis.',
      'A 15-year model of income, expenditure and capital expenditure, with annual profit and loss (EBIT, EBITDA, pre-tax profit), balance sheet and project IRR.',
      'Institutional and financial governance models with PPP frameworks, cost recovery and sustainability mechanisms.',
    ],
    links: [],
    photo: '',
    services: ['economic-assessment'],
    sectors: ['private-sector', 'macroeconomic-fiscal'],
    note: 'Source: CV, FORM TECH-6 (dates corrected from the old site\'s 2017).',
  },
  {
    id: 'jolshiri-aqua-green-city-feasibility',
    status: 'published',
    featured: false,
    title: 'Jolshiri Aqua Green City: economic, social, financial and market feasibility',
    client: 'Bangladesh Army and ZTENCO',
    institutions: ['Bangladesh Army', 'ZTENCO'],
    role: 'Team leader',
    reference: 'Army Officers Housing Scheme town development project',
    place: 'Dhaka, Bangladesh',
    period: 'May 2019 – June 2020',
    start: 2019,
    end: 2020,
    places: ['BD-dhaka'],
    summary:
      'Economic, social, financial and market feasibility study for a new town development, with a 10-year projection, pricing and an investment and funding plan.',
    challenge:
      'A large planned township has to work as a city and as a business. The sponsors needed to know what it would cost, how to price plots across categories, how to fund it, and whether the borrowing company could carry the debt.',
    approach: [
      'Led delivery: proposal, study design, budget, research and survey teams, stakeholder coordination and the final report.',
      'A 10-year projection with business strategy and a marketing plan, based on economic and social cost-benefit analysis and a market study.',
      'Capital requirement schedule, yearly expenditure and liabilities analysis, working capital and sensitivity analysis.',
      'Plot- and item-wise market segmentation with cost-versus-benefit pricing.',
      'Financial investment plan, funding options, creditworthiness, equity and IRR analysis, payback period and cash-flow forecast.',
    ],
    links: [],
    photo: '',
    services: ['economic-assessment'],
    sectors: ['private-sector', 'cities-municipal-finance'],
    note: 'Source: CV, FORM TECH-6.',
  },
  {
    id: 'fat-survey-bangladesh',
    status: 'published',
    featured: true,
    title: 'Firm-level Adoption of Technology survey: gearing up the future of manufacturing',
    client: 'World Bank',
    institutions: ['World Bank'],
    role: 'Ran the Bangladesh survey from questionnaire design to report (short-term consultant)',
    reference: 'Firm-level Adoption of Technology (FAT) Survey 2019; policy report for eight manufacturing sectors',
    place: 'Bangladesh',
    period: 'February 2019 – December 2020',
    start: 2019,
    end: 2020,
    places: ['BD'],
    summary:
      'The Bangladesh arm of a World Bank flagship survey of technology adoption across 1,200 manufacturing firms, identifying barriers to productivity and the policy reforms that could remove them.',
    challenge:
      'Bangladesh\'s manufacturing has grown on low wages, but staying competitive means adopting better technology. Nobody knew how far firms had actually adopted it, what held them back, or which reforms would help.',
    approach: [
      'Supported the Task Team Leader in research design, implementation and policy advocacy.',
      'Ran the Bangladesh project end to end: questionnaire design, survey implementation, data analysis and report writing.',
      'Trained firms for the survey and guided survey teams on questionnaire programming, monitoring and data-quality control.',
      'Organised high-level dissemination seminars with the World Bank\'s lead economists.',
    ],
    links: [
      { label: 'Gearing Up for the Future of Manufacturing in Bangladesh (World Bank, 2021)', href: 'http://hdl.handle.net/10986/35879' },
      {
        label: 'Bridging the Technological Divide: Technology Adoption by Firms in Developing Countries (World Bank, 2022)',
        href: 'https://openknowledge.worldbank.org/entities/publication/ee3abd08-33db-41b9-86f7-9b3176632083',
      },
    ],
    photo: 'tech-adoption-slide',
    services: ['program-survey-design', 'macro-sector-policy'],
    sectors: ['private-sector'],
    note: 'Source: CV, FORM TECH-6 and EU CV (1,200 firms).',
  },
  {
    id: 'rct-energy-efficient-motors',
    status: 'published',
    featured: false,
    title: 'How managers\' beliefs about new technology evolve: an RCT on energy-efficient stitching motors',
    client: 'World Bank, Office of the Chief Economist for South Asia',
    institutions: ['World Bank', 'Johns Hopkins University', 'Columbia University'],
    role: 'Research design, piloting, field coordination and data analysis (short-term consultant)',
    reference: 'Randomised controlled trial, textile and leather sector',
    place: 'Bangladesh',
    period: 'February 2019 – June 2022',
    start: 2019,
    end: 2022,
    places: ['BD'],
    summary:
      'A randomised controlled trial testing whether information changes how factory managers judge, and adopt, energy-efficient stitching motors.',
    challenge:
      'Energy-efficient motors pay for themselves, yet many garment and leather factories do not install them. Is it cost, risk, or simply what managers believe? Only a rigorous experiment could tell.',
    approach: [
      'Assisted the principal investigators with research design, piloting and rollout of the informational interventions.',
      'Coordinated implementation, data collection and field operations.',
      'Analysed the data with professors from Columbia University and Johns Hopkins University and World Bank lead economists.',
    ],
    links: [],
    photo: '',
    services: ['merla', 'program-survey-design'],
    sectors: ['private-sector', 'climate-energy'],
    note: 'Source: CV, FORM TECH-6.',
  },
  {
    id: 'ldc-graduation-policy-reform',
    status: 'published',
    featured: true,
    title: 'Bangladesh\'s LDC graduation: mitigation actions and opportunities for EU engagement',
    client: 'European Commission',
    institutions: ['European Commission', 'TIEG'],
    role: 'Economist and deputy team leader',
    reference: 'EC FWC SIEA Lot 2: Infrastructures, Sustainable Growth and Jobs',
    place: 'Bangladesh',
    period: 'January 2020 – May 2021',
    start: 2020,
    end: 2021,
    places: ['BD'],
    summary:
      'Analysis for the European Union and its member states on how to support a smooth and inclusive graduation from least developed country status: risk mitigation, trade, business, financing and market opportunities.',
    challenge:
      'Graduating from LDC status is a milestone, but it ends preferential trade terms and some concessional support that Bangladesh\'s exporters rely on. The EU, its largest export market, wanted to know where its support could soften the shock and open new opportunities.',
    approach: [
      'Reviewed existing analyses and identified the diagnostic gaps: productive capacity, markets, trade integration, investment and financing, cost-benefit and vulnerability.',
      'Identified the key areas where EU intervention could offset the loss of international support measures and open investment.',
      'Acted as focal point with the EU Delegation, embassies, the Prime Minister\'s Office, the Planning Commission, the Ministries of Finance and Commerce, trade bodies and industry associations.',
    ],
    links: [],
    photo: '',
    services: ['macro-sector-policy'],
    sectors: ['macroeconomic-fiscal', 'private-sector'],
    note: 'Source: CV, FORM TECH-6. The old site paired this with the World Bank; the CV gives the European Commission and TIEG.',
  },
  {
    id: 'bmdf-municipal-finance-transformation',
    status: 'published',
    featured: false,
    title: 'Green municipal infrastructure: operation support and capacity building for BMDF',
    client: 'World Bank and the Ministry of Finance (Bangladesh Municipal Development Fund)',
    institutions: ['World Bank', 'Ministry of Finance', 'Bangladesh Municipal Development Fund'],
    role: 'Economic, business, financial and market plan development specialist',
    reference: 'Municipal Governance and Services Project (MGSP)',
    place: 'Bangladesh',
    period: 'September 2019 – June 2020',
    start: 2019,
    end: 2020,
    places: ['BD'],
    summary:
      'Support to the Bangladesh Municipal Development Fund to design bankable, environmentally responsible municipal infrastructure and a financially sustainable business model.',
    challenge:
      'Bangladesh\'s pourashavas (municipalities) need roads, lighting, drainage and waste systems, but few have the planning tools or revenue to finance them. The Fund needed a pipeline of bankable green projects and a business model that would last.',
    approach: [
      'Designed bankable, environment-friendly projects: solar-powered public facilities, energy-efficient street lighting and waste-to-energy systems.',
      'Used GIS data for pourashava planning and built investment pipelines from geospatial analysis.',
      'A 10-year financial roadmap tied to national plans and SDG targets, with funding mechanisms and revenue models.',
      'Economic and financial cost-benefit analysis of renewable energy proposals: viability, payback and social impact.',
      'Financial risk assessment and sensitivity analysis.',
    ],
    links: [],
    photo: '',
    services: ['economic-assessment', 'climate-esg', 'macro-sector-policy'],
    sectors: ['cities-municipal-finance', 'public-governance', 'climate-energy'],
    note: 'Source: CV, FORM TECH-6.',
  },
  {
    id: 'cem-bangladesh-india',
    status: 'published',
    featured: false,
    title: 'Country Economic Memorandums for Bangladesh and India',
    client: 'World Bank',
    institutions: ['World Bank'],
    role: 'Thematic and sectoral research (short-term consultant)',
    reference: 'Macro-fiscal team, South Asia',
    place: 'Bangladesh and India',
    period: 'June 2021 – April 2022',
    start: 2021,
    end: 2022,
    places: ['BD', 'IND'],
    summary:
      'Research for the World Bank\'s Country Economic Memorandums: the opportunities and constraints for trade and private sector-led growth, in light of the pandemic and LDC graduation.',
    challenge:
      'A Country Economic Memorandum sets a long-run view of a country\'s development priorities. After the pandemic and with LDC graduation ahead, the World Bank needed fresh evidence on which reforms could foster inclusive growth.',
    approach: [
      'Thematic and sectoral research on trade and private sector-led growth.',
      'Reports for the preparation of the memorandums for Bangladesh and India.',
      'Key informant interviews.',
    ],
    links: [],
    photo: '',
    services: ['macro-sector-policy'],
    sectors: ['macroeconomic-fiscal', 'private-sector'],
    note: 'Source: CV, FORM TECH-6.',
  },
  {
    id: 'green-trade-policy-reform',
    status: 'published',
    featured: false,
    title: 'Green trade, investment and transition policy reform',
    client: 'World Bank',
    institutions: ['World Bank'],
    role: 'Policy research (short-term consultant)',
    reference: 'Scoping study and stakeholder mapping',
    place: 'Bangladesh, India and Vietnam',
    period: 'June 2021 – April 2022',
    start: 2021,
    end: 2022,
    places: ['BD', 'IND', 'VNM'],
    summary:
      'A scoping study and stakeholder mapping for transformative green trade, investment and transition policy reform in Bangladesh, India and Vietnam.',
    challenge:
      'Trade in environmental goods and services can speed the climate transition, but in Bangladesh the policies, institutions and finance behind it were scattered and incomplete.',
    approach: [
      'Contributed to the report "Act now, there is no time to wait for greening trade: the case of Bangladesh".',
      'Prepared "Status of current policies and strategies, and policy gaps in trade, investment and finance for environmental goods and services in Bangladesh".',
      'Prepared an institutional map of trade, investment and financing for environmental goods and services in Bangladesh.',
    ],
    links: [],
    photo: '',
    services: ['macro-sector-policy', 'climate-esg'],
    sectors: ['climate-energy', 'macroeconomic-fiscal'],
    note: 'Source: CV, FORM TECH-6.',
  },
  {
    id: 'unctad-productive-capacities',
    status: 'published',
    featured: false,
    title: 'Productive capacities gap assessment for Bangladesh',
    client: 'UNCTAD and the Centre for Policy Dialogue',
    institutions: ['UNCTAD', 'Centre for Policy Dialogue'],
    role: 'Economist (visiting research fellow)',
    reference: '',
    place: 'Bangladesh',
    period: 'December 2021 – January 2022',
    start: 2021,
    end: 2022,
    places: ['BD'],
    summary:
      'The analytical basis for Bangladesh\'s "graduation with momentum" strategy: an assessment of the country\'s productive capacities and the constraints that bind them.',
    challenge:
      'To keep growing after LDC graduation, Bangladesh has to produce more, and more varied, goods and services. UNCTAD needed to know where the country\'s productive capacities fall short and why.',
    approach: [
      'Conducted the productive capacities gap assessment and prepared the analytical documents.',
      'Analysed productive capacity scores, performance and the binding constraints on structural transformation, including institutional limits and implementation gaps.',
      'Examined comparative advantage and made country-specific policy recommendations.',
    ],
    links: [],
    photo: '',
    services: ['macro-sector-policy'],
    sectors: ['macroeconomic-fiscal', 'private-sector'],
    note: 'Source: CV, FORM TECH-6.',
  },
  {
    id: 'services-trade-policy-index',
    status: 'published',
    featured: false,
    title: 'Global Services Trade Policy Database and Index: Bangladesh',
    client: 'World Bank and the World Trade Organization',
    institutions: ['World Bank', 'World Trade Organization'],
    role: 'Policy research and data collection (short-term consultant)',
    reference: '',
    place: 'Bangladesh',
    period: 'March 2020 – June 2022',
    start: 2020,
    end: 2022,
    places: ['BD'],
    summary:
      'Bangladesh\'s entry in the joint WTO and World Bank database and index of the policies that govern trade in services.',
    challenge:
      'Services are a growing share of trade, but the rules that restrict them are hard to compare across countries. The WTO and World Bank built a global database; Bangladesh\'s applied policies had to be documented sector by sector.',
    approach: [
      'Policy and research work to build the database and index for Bangladesh.',
      'Gathered applied policies and regulations across sectors and sub-sectors through desk research and interviews.',
    ],
    links: [],
    photo: '',
    services: ['macro-sector-policy'],
    sectors: ['macroeconomic-fiscal', 'public-governance'],
    note: 'Source: CV, FORM TECH-6.',
  },
  {
    id: 'dscc-vision-2050',
    status: 'published',
    featured: false,
    title: 'Vision 2050: modernising Dhaka South City Corporation',
    client: 'Dhaka South City Corporation',
    institutions: ['Dhaka South City Corporation'],
    role: 'Municipal governance and finance expert',
    reference: 'Dhaka South City Modernisation Study (Mayor\'s Vision 2050: Modern Dhaka)',
    place: 'Dhaka, Bangladesh',
    period: 'February 2020 – September 2020',
    start: 2020,
    end: 2020,
    places: ['BD-dhaka'],
    summary:
      'Preparatory studies for the city\'s Vision 2050: a smart, resilient and inclusive Dhaka, with a financing and investment plan and governance reforms.',
    challenge:
      'Dhaka is one of the world\'s most crowded cities. A long-term vision needs more than ambition: it needs a plan for financing, institutions and the business models that will keep services running.',
    approach: [
      'Preparatory studies for city infrastructure, services and governance.',
      'The city financing and investment plan, and a local institutions and governance reform plan.',
      'Assessment of economic prospects, with business and revenue models for carrying out the plan.',
    ],
    links: [],
    photo: '',
    services: ['economic-assessment', 'macro-sector-policy'],
    sectors: ['cities-municipal-finance', 'public-governance'],
    note: 'Source: CV, FORM TECH-6.',
  },
  {
    id: 'halow-plus-worker-health',
    status: 'published',
    featured: true,
    title: 'HALOW+: health access and linkage opportunities for garment workers',
    client: 'Business Innovation Facility (DFID-funded)',
    institutions: ['Business Innovation Facility (DFID)', 'PwC UK', 'Tufts University', 'GSK', 'Marks & Spencer', 'CARE International'],
    role: 'Monitoring and evaluation adviser and impact evaluation expert for the whole partnership',
    reference: '',
    place: 'Bangladesh',
    period: 'April 2018 – April 2020',
    start: 2018,
    end: 2020,
    places: ['BD'],
    summary:
      'A multi-partner programme to build a health service market for ready-made garment workers, improve their working and health conditions, and raise factory productivity.',
    challenge:
      'Garment workers, most of them women, often cannot reach basic health care, and factories lose output when workers fall ill. Brands, a pharmaceutical company, an NGO and researchers came together to test whether better health access could be good for workers and good for business.',
    approach: [
      'Economic, financial and cost-benefit analysis across the partnership.',
      'Built health and productivity databases and quantitative business models that informed welfare investment decisions.',
      'Implemented a randomised controlled trial: data collection, analysis and reporting.',
      'Managed the monitoring and evaluation team, project monitoring and data-quality control.',
      'Collected factory data for PwC\'s business value analysis.',
    ],
    links: [],
    photo: '',
    services: ['merla', 'economic-assessment'],
    sectors: ['private-sector', 'social-protection', 'monitoring-evaluation'],
    note: 'Source: CV, FORM TECH-6.',
  },
  {
    id: 'dsip-me-results-framework',
    status: 'published',
    featured: false,
    title: 'Dhaka Sanitation Improvement Project: monitoring and evaluation and results framework',
    client: 'World Bank, with SODEV International Consulting',
    institutions: ['World Bank', 'SODEV International Consulting', 'Dhaka WASA'],
    role: 'Monitoring and evaluation and results measurement expert (international)',
    reference: 'Preparatory TA for the Dhaka sewerage network, wastewater treatment, non-network sanitation and septage management',
    place: 'Dhaka, Bangladesh',
    period: 'April 2018 – June 2019',
    start: 2018,
    end: 2019,
    places: ['BD-dhaka'],
    summary:
      'The monitoring and evaluation and results framework for the five-year Dhaka Sanitation Improvement Project with Dhaka WASA.',
    challenge:
      'Most of Dhaka is not connected to a sewer. The project combines new sewerage and wastewater treatment with non-network sanitation where sewers are not feasible, and a new project management unit. Its results had to be measurable from the start.',
    approach: [
      'Designed the monitoring and evaluation and results framework for the project\'s five-year operation.',
      'Covered all four components: institutional support, sewerage and treatment, non-network sanitation in the Pagla treatment-plant area, and project management.',
    ],
    links: [],
    photo: '',
    services: ['merla'],
    sectors: ['cities-municipal-finance', 'monitoring-evaluation'],
    note: 'Source: CV, FORM TECH-6. The old site called it the Dhaka Sewerage Improvement Project; the CV says Sanitation.',
  },
  {
    id: 'digital-informality-survey-bangladesh',
    status: 'published',
    featured: false,
    title: 'Bangladesh Digital and Informality Survey 2021',
    client: 'World Bank',
    institutions: ['World Bank'],
    role: 'Survey design, programming and analysis (short-term consultant)',
    reference: '',
    place: 'Bangladesh',
    period: 'June 2020 – December 2021',
    start: 2020,
    end: 2021,
    places: ['BD'],
    summary:
      'Evidence on how digital technologies and new business models affect informality in South Asia.',
    challenge:
      'Digital platforms could help small informal businesses grow and formalise, or deepen informality. The World Bank needed survey evidence from Bangladesh to know which.',
    approach: [
      'Helped the Task Team Leader prepare the questionnaire and survey design.',
      'Programmed the survey and analysed the data.',
      'Reported findings and progress to the client.',
    ],
    links: [{ label: 'World Bank Open Knowledge Repository', href: 'https://openknowledge.worldbank.org/handle/10986/39446' }],
    photo: '',
    services: ['program-survey-design', 'macro-sector-policy'],
    sectors: ['private-sector'],
    note: 'Source: EU CV. The old site\'s "500 suppliers" figure is not in the CV, so it was removed.',
  },
  {
    id: 'covid-business-pulse-survey',
    status: 'published',
    featured: false,
    title: 'COVID-19 impact on businesses: Business Pulse Survey 2020',
    client: 'World Bank',
    institutions: ['World Bank'],
    role: 'Research and survey preparation (short-term consultant)',
    reference: '',
    place: 'Bangladesh',
    period: 'June 2020 – December 2021',
    start: 2020,
    end: 2021,
    places: ['BD'],
    summary: 'A rapid survey of how the COVID-19 pandemic affected businesses in Bangladesh.',
    challenge:
      'When the pandemic shut markets and factories, policy-makers needed to know quickly which firms were hurt, how badly, and what support would reach them.',
    approach: [
      'Researched the impact of the pandemic on businesses in Bangladesh.',
      'Prepared survey materials and questionnaires with the Task Team Leader.',
    ],
    links: [],
    photo: '',
    services: ['program-survey-design'],
    sectors: ['private-sector', 'macroeconomic-fiscal'],
    note: 'Source: EU CV and FORM TECH-6 (other assignments).',
  },
  {
    id: 'sesip-seip-capacity-assessment',
    status: 'published',
    featured: false,
    title: 'Management capacity in education and skills programmes (SESIP, SEIP)',
    client: 'Asian Development Bank (ADB)',
    institutions: ['Asian Development Bank'],
    role: 'Project assessment consultant',
    reference: '',
    place: 'Bangladesh',
    period: 'June 2020',
    start: 2020,
    end: 2020,
    places: ['BD'],
    summary: 'Assessment for capacity building of management in two ADB-supported education and skills programmes.',
    challenge: 'Large education and skills programmes succeed or fail on the strength of the teams that manage them.',
    approach: ['Assessed the management of the Secondary Education Sector Investment Program and the Skills for Employment Investment Program.'],
    links: [],
    photo: '',
    services: ['merla'],
    sectors: ['education-skills'],
    note: 'Source: FORM TECH-6 (other assignments).',
  },
  {
    id: 'digital-identity-civil-registry-interoperability',
    status: 'published',
    featured: false,
    title: 'National digital identity and civil registry interoperability',
    client: 'Client to be confirmed',
    institutions: [],
    role: '',
    reference: '',
    place: 'Place to be confirmed',
    period: 'Year to be confirmed',
    start: 2024,
    end: 2024,
    places: [],
    summary:
      'Interoperability and data-governance architecture to connect fragmented civil registries and support integrated social-protection delivery: an interoperability blueprint, a data governance and privacy framework, and an implementation road map.',
    challenge:
      'When birth, identity and social-protection records live in separate systems, people fall through the gaps and support reaches the wrong hands. Connecting the registries safely needs common standards, clear data governance and privacy protection.',
    approach: [
      'An interoperability blueprint for the civil registries.',
      'A data governance and privacy framework.',
      'An implementation road map.',
    ],
    links: [],
    photo: '',
    services: ['macro-sector-policy'],
    sectors: ['public-governance', 'social-protection'],
    note:
      'Published on IP3\'s instruction (2 October 2026). Not found in the CVs supplied, so client, place, period and role stay empty and are hidden. The old site gave "UNDP / government, 2024"; confirm and fill in. The start year 2024 is used only for ordering.',
  },
  {
    id: 'secondary-stem-tvet-curriculum-modernisation',
    status: 'published',
    featured: false,
    title: 'Secondary STEM and TVET curriculum modernisation',
    client: 'Client to be confirmed',
    institutions: [],
    role: '',
    reference: '',
    place: 'Place to be confirmed',
    period: 'Year to be confirmed',
    start: 2024,
    end: 2024,
    places: [],
    summary:
      'Modernisation of secondary STEM and vocational (TVET) curricula to match labour-market and climate-era skills, with a teacher accreditation model: a curriculum framework, a modular accreditation system and an implementation plan.',
    challenge:
      'Secondary science and vocational curricula were written for an economy that is disappearing. Students need skills for automation and a changing climate, and teachers need a way to be accredited in them.',
    approach: ['A curriculum framework for secondary STEM and TVET.', 'A modular teacher accreditation system.', 'An implementation plan.'],
    links: [],
    photo: '',
    services: ['program-survey-design', 'macro-sector-policy'],
    sectors: ['education-skills'],
    note:
      'Published on IP3\'s instruction (2 October 2026). Not found as a separate assignment in the CVs; it may be part of the ADB NextGen TVET feasibility study (2024). If so, merge the two. The old site gave "UNESCO / GPE / government, 2024". The start year 2024 is used only for ordering.',
  },

  /* ---- Kept for the record, not shown: before 2018 or delivered through another firm. ---- */
  {
    id: 'sez-equity-investment-policy',
    status: 'verify',
    featured: false,
    title: 'Equity investment policy and guidelines for BIFFL and BEZA',
    client: 'New Vision Solutions Limited, with JICA and the Japan Development Institute',
    institutions: ['JICA'],
    role: 'Executive director and head of research, NVSL',
    reference: '',
    place: 'Bangladesh',
    period: 'January 2017 – December 2017',
    start: 2017,
    end: 2017,
    places: ['BD'],
    summary:
      'An equity investment policy and special purpose company structures for an infrastructure finance fund and the economic zones authority.',
    challenge: '',
    approach: [],
    links: [],
    photo: '',
    services: ['economic-assessment', 'macro-sector-policy'],
    sectors: ['private-sector', 'macroeconomic-fiscal'],
    note: 'Hidden: 2017, delivered through New Vision Solutions Limited, not IP3. IP3 asked for the portfolio to run from 2018.',
  },
  {
    id: 'global-leap-results-based-financing',
    status: 'verify',
    featured: false,
    title: 'Clean Energy Financing Program for the Global Lighting and Energy Access Partnership',
    client: 'CLASP International and Prokaushali Shangsad Ltd',
    institutions: ['CLASP'],
    role: 'Senior associate, clean energy access',
    reference: '',
    place: 'Bangladesh',
    period: 'June 2015 – June 2016',
    start: 2015,
    end: 2016,
    places: ['BD'],
    summary: 'Results-based financing to speed the adoption of off-grid solar home systems.',
    challenge: '',
    approach: [],
    links: [],
    photo: '',
    services: ['economic-assessment', 'climate-esg', 'merla'],
    sectors: ['climate-energy', 'private-sector'],
    note: 'Hidden: before 2018. The CV settles the year question (June 2015 – June 2016).',
  },
  {
    id: 'esmap-astae-evaluation',
    status: 'verify',
    featured: false,
    title: 'Evaluation of World Bank ESMAP and ASTAE programmes',
    client: 'World Bank and ICF International',
    institutions: ['World Bank'],
    role: 'External evaluator',
    reference: '',
    place: 'Bangladesh and Nepal',
    period: 'August 2015 – June 2016',
    start: 2015,
    end: 2016,
    places: ['BD', 'NPL'],
    summary:
      'Financial, economic and social impact evaluation of renewable energy projects under ESMAP and ASTAE in Bangladesh and Nepal.',
    challenge: '',
    approach: [],
    links: [],
    photo: '',
    services: ['economic-assessment', 'climate-esg', 'merla'],
    sectors: ['climate-energy', 'monitoring-evaluation'],
    note: 'Hidden: before 2018.',
  },
];
