import { Fragment, useEffect, useId, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { api, ApiError } from '../../lib/apiClient';

type Turn = { role: 'user' | 'assistant'; content: string };

const TEXT = {
  en: {
    open: 'Ask IP3',
    title: 'Ask IP3',
    intro: 'Ask about our work, services or team. Answers come only from this website; for anything specific, the team will reply through the contact page.',
    placeholder: 'Type your question',
    send: 'Ask',
    close: 'Close',
    thinking: 'Looking through the site…',
    note: 'Answers are generated by AI from this website and can be wrong. Questions are not stored.',
    suggestions: ['What has IP3 done in education?', 'Who leads IP3?', 'Can you appraise an infrastructure project?', 'Have you worked on climate finance?'],
    errors: {
      RATE_LIMITED: 'You have asked a lot of questions in a short time. Please try again in a few minutes.',
      DAILY_LIMIT: 'The assistant has answered as many questions as it can today. Please write to us through the contact page.',
      TOO_LONG: 'Please keep your question under 800 characters.',
      default: 'The assistant could not answer just now. Please try again, or write to us through the contact page.',
    } as Record<string, string>,
  },
  bn: {
    open: 'আইপিথ্রি-কে জিজ্ঞাসা করুন',
    title: 'আইপিথ্রি-কে জিজ্ঞাসা করুন',
    intro: 'আমাদের কাজ, সেবা বা দল সম্পর্কে প্রশ্ন করুন। উত্তর শুধু এই ওয়েবসাইটের তথ্য থেকে দেওয়া হয়।',
    placeholder: 'আপনার প্রশ্ন লিখুন',
    send: 'জিজ্ঞাসা',
    close: 'বন্ধ করুন',
    thinking: 'ওয়েবসাইটে খোঁজা হচ্ছে…',
    note: 'উত্তরগুলো এই ওয়েবসাইট থেকে কৃত্রিম বুদ্ধিমত্তা দিয়ে তৈরি এবং ভুল হতে পারে। প্রশ্ন সংরক্ষণ করা হয় না।',
    suggestions: ['শিক্ষা খাতে আইপিথ্রি কী কাজ করেছে?', 'আইপিথ্রি-র নেতৃত্বে কারা?', 'জলবায়ু অর্থায়নে আপনাদের অভিজ্ঞতা আছে?'],
    errors: {
      RATE_LIMITED: 'অল্প সময়ে অনেক প্রশ্ন করা হয়েছে। কয়েক মিনিট পরে আবার চেষ্টা করুন।',
      DAILY_LIMIT: 'আজকের মতো প্রশ্নের সীমা পূর্ণ হয়েছে। যোগাযোগ পাতা থেকে আমাদের লিখুন।',
      TOO_LONG: 'প্রশ্নটি ৮০০ অক্ষরের মধ্যে রাখুন।',
      default: 'এই মুহূর্তে উত্তর দেওয়া গেল না। আবার চেষ্টা করুন, অথবা যোগাযোগ পাতা থেকে আমাদের লিখুন।',
    } as Record<string, string>,
  },
};

/**
 * Renders an answer: paragraphs, "- " list lines, and markdown links. Site paths become router links and https
 * links open in a new tab; anything else stays plain text, so a model answer can never inject markup.
 */
function Answer({ text }: { text: string }) {
  const inline = (s: string, key: string): ReactNode[] => {
    const out: ReactNode[] = [];
    const re = /\[([^\]]+)\]\(([^)\s]+)\)/g;
    let last = 0;
    let m: RegExpExecArray | null;
    let n = 0;
    while ((m = re.exec(s))) {
      if (m.index > last) out.push(s.slice(last, m.index));
      const [, label, href] = m;
      if (href!.startsWith('/') && !href!.startsWith('//')) {
        out.push(
          <Link key={`${key}-${n++}`} to={href!} className="font-semibold text-teal-deep underline underline-offset-4">
            {label}
          </Link>,
        );
      } else if (/^https:\/\//.test(href!)) {
        out.push(
          <a key={`${key}-${n++}`} href={href} target="_blank" rel="noopener noreferrer" className="font-semibold text-teal-deep underline underline-offset-4">
            {label}
            <span className="sr-only"> (opens in a new tab)</span>
          </a>,
        );
      } else out.push(label!);
      last = m.index + m[0].length;
    }
    if (last < s.length) out.push(s.slice(last));
    return out.map((x, i) => (typeof x === 'string' ? x.replace(/\*\*/g, '') : <Fragment key={`${key}-f${i}`}>{x}</Fragment>));
  };
  const blocks = text.split(/\n{2,}/);
  return (
    <>
      {blocks.map((b, i) => {
        const lines = b.split('\n').filter(Boolean);
        if (lines.length && lines.every((l) => /^\s*[-*•]\s+/.test(l))) {
          return (
            <ul key={i} className="mt-2 grid gap-1 first:mt-0">
              {lines.map((l, j) => (
                <li key={j} className="flex gap-2">
                  <span aria-hidden="true" className="mt-[0.6em] h-1.5 w-1.5 shrink-0 rounded-full bg-teal-deep" />
                  <span>{inline(l.replace(/^\s*[-*•]\s+/, ''), `${i}-${j}`)}</span>
                </li>
              ))}
            </ul>
          );
        }
        return (
          <p key={i} className="mt-2 first:mt-0">
            {inline(lines.join(' '), String(i))}
          </p>
        );
      })}
    </>
  );
}

/**
 * The Ask IP3 assistant: a button that opens a small panel. It appears only when the server says the assistant
 * is switched on (ANTHROPIC_API_KEY set), so a deploy without a key shows nothing. Never on the admin console.
 */
export function AskIP3() {
  const { pathname } = useLocation();
  const t = TEXT[pathname === '/bn' ? 'bn' : 'en'];
  const [enabled, setEnabled] = useState(false);
  const [open, setOpen] = useState(false);
  const [turns, setTurns] = useState<Turn[]>([]);
  const [draft, setDraft] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const buttonRef = useRef<HTMLButtonElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const logRef = useRef<HTMLDivElement>(null);
  const titleId = useId();

  useEffect(() => {
    let live = true;
    api
      .get<{ enabled: boolean }>('/ask/status')
      .then((r) => live && setEnabled(Boolean(r?.enabled)))
      .catch(() => live && setEnabled(false));
    return () => {
      live = false;
    };
  }, []);

  // Focus follows the panel: into the question box on open, back to the launcher on close.
  const wasOpen = useRef(false);
  useEffect(() => {
    if (open) inputRef.current?.focus();
    else if (wasOpen.current) buttonRef.current?.focus();
    wasOpen.current = open;
  }, [open]);

  useEffect(() => {
    logRef.current?.scrollTo({ top: logRef.current.scrollHeight });
  }, [turns, busy]);

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setOpen(false);
    };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open]);

  if (!enabled) return null;

  const ask = async (question: string) => {
    const q = question.trim();
    if (!q || busy) return;
    const next: Turn[] = [...turns, { role: 'user', content: q }];
    setTurns(next);
    setDraft('');
    setError('');
    setBusy(true);
    inputRef.current?.focus(); // a suggestion button disappears once asked; keep focus in the panel
    try {
      const res = await api.post<{ answer: string }>('/ask', { messages: next });
      setTurns([...next, { role: 'assistant', content: res.answer }]);
    } catch (err) {
      const code = err instanceof ApiError ? err.code : '';
      setError(t.errors[code || ''] || t.errors.default!);
      setTurns(turns); // drop the unanswered question so the conversation stays well-formed
      setDraft(q);
    } finally {
      setBusy(false);
    }
  };

  const onSubmit = (e: FormEvent) => {
    e.preventDefault();
    void ask(draft);
  };

  return (
    <>
      {!open ? (
        <button
          ref={buttonRef}
          type="button"
          onClick={() => setOpen(true)}
          aria-expanded={open}
          className="t-label fixed bottom-4 right-4 z-40 inline-flex min-h-12 items-center gap-2 rounded-full bg-signal px-5 text-midnight shadow-lg transition-transform hover:-translate-y-0.5 sm:bottom-6 sm:right-6"
        >
          <svg viewBox="0 0 20 20" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true">
            <path d="M3 4.5h14v9H8l-4 3v-3H3z" strokeLinejoin="round" />
          </svg>
          {t.open}
        </button>
      ) : null}
      {open ? (
        <section
          role="dialog"
          aria-modal="false"
          aria-labelledby={titleId}
          className="on-paper fixed inset-x-2 bottom-2 z-50 flex max-h-[min(36rem,calc(100svh-5rem))] flex-col rounded-lg border border-midnight/15 shadow-2xl sm:inset-x-auto sm:bottom-6 sm:right-6 sm:w-[26rem]"
        >
          <header className="flex items-center justify-between border-b border-midnight/15 px-5 py-3">
            <h2 id={titleId} className="font-serif text-xl">
              {t.title}
            </h2>
            <button
              type="button"
              onClick={() => setOpen(false)}
              className="t-ui inline-flex min-h-11 items-center px-2 text-ink-soft underline-offset-4 hover:underline"
            >
              {t.close}
            </button>
          </header>
          <div ref={logRef} aria-live="polite" className="t-ui flex-1 overflow-y-auto px-5 py-4">
            {turns.length === 0 ? (
              <>
                <p className="text-ink-soft">{t.intro}</p>
                <ul className="mt-4 grid gap-2">
                  {t.suggestions.map((s) => (
                    <li key={s}>
                      <button
                        type="button"
                        onClick={() => void ask(s)}
                        className="w-full rounded-md border border-midnight/20 px-3 py-2 text-left hover:border-teal-deep hover:bg-white"
                      >
                        {s}
                      </button>
                    </li>
                  ))}
                </ul>
              </>
            ) : (
              <ol className="grid gap-4">
                {turns.map((turn, i) => (
                  <li key={i} className={turn.role === 'user' ? 'ml-8 rounded-md bg-midnight px-3 py-2 text-ivory' : 'mr-4'}>
                    <span className="sr-only">{turn.role === 'user' ? 'You asked: ' : 'Answer: '}</span>
                    {turn.role === 'user' ? turn.content : <Answer text={turn.content} />}
                  </li>
                ))}
                {busy ? <li className="text-ink-soft">{t.thinking}</li> : null}
              </ol>
            )}
            {error ? (
              <p role="alert" className="mt-4 rounded-md border border-amber-deep/40 bg-amber/10 px-3 py-2">
                {error}
              </p>
            ) : null}
          </div>
          <form onSubmit={onSubmit} className="border-t border-midnight/15 px-5 py-3">
            <label htmlFor={`${titleId}-q`} className="sr-only">
              {t.placeholder}
            </label>
            <div className="flex items-end gap-2">
              <textarea
                id={`${titleId}-q`}
                ref={inputRef}
                rows={2}
                maxLength={800}
                value={draft}
                onChange={(e) => setDraft(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault();
                    void ask(draft);
                  }
                }}
                placeholder={t.placeholder}
                className="t-ui min-h-11 flex-1 resize-none rounded-md border border-midnight/25 bg-white px-3 py-2"
              />
              <button type="submit" disabled={busy || !draft.trim()} className="btn btn-ink min-h-11 px-4 disabled:opacity-50">
                {t.send}
              </button>
            </div>
            <p className="t-ui mt-2 text-[0.8rem] text-ink-soft">{t.note}</p>
          </form>
        </section>
      ) : null}
    </>
  );
}
